---
title: "Problem2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(lubridate)
library(p8105.datasets)
data(ny_noaa)
```

```{r}
ny_noaa_2002_apr =
  ny_noaa |>
  janitor::clean_names() |>
  #only analysis data from April 2002 and drop missing data
  mutate(date = ymd(date)) |>
  filter(year(date) == 2002 & month(date) == 04) |>
  filter(!is.na(prcp) & !is.na(snow) & !is.na(snwd) & !is.na(tmax) & !is.na(tmin)) |>
  mutate(across(c(prcp, snow, snwd, tmin, tmax), as.numeric),
    #convert from tenths of units to standard units (mm and °C)
    prcp_mm = prcp / 10,
    tmax_c = tmax / 10,
    tmin_c = tmin / 10)
```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa_2002_apr |>
  mutate(
    text_label = str_c(
      "ID: ", id,
      "\nDate: ", date, 
      "\nPrecipitation (mm): ", prcp_mm,
      "\nSnowfall (mm): ", snow,
      "\nSnow Depth (mm): ", snwd)) |>
  plot_ly(
    x = ~prcp_mm, 
    y = ~snow, 
    color = ~snwd,
    text = ~text_label,
    hoverinfo = 'text',
    type = "scatter", 
    mode = "markers", 
    alpha = 0.7) |>
  layout(
    title = "Snowfall vs. Precipitation in April 2002",
    xaxis = list(title = "Precipitation (mm)"),
    yaxis = list(title = "Snowfall (mm)")) |>
  colorbar(title = "Snow Depth (mm)")
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B

```{r}
#Box Plot for showing max temperature distribution of 4 weeks in April 2002
ny_noaa_2002_apr |>
  mutate(
    week_of_month = case_when(
      day(date) <= 7  ~ "Week 1",
      day(date) <= 14 ~ "Week 2",
      day(date) <= 21 ~ "Week 3",
      TRUE            ~ "Week 4"),
    week_of_month = factor(week_of_month, 
                           levels = c("Week 1", "Week 2", "Week 3", "Week 4"))) |>
  plot_ly(
    x = ~week_of_month, 
    y = ~tmax_c, 
    type = "box",
    color = ~week_of_month) |>
  layout(
    title = "Distribution of Weekly Highest Temperatures in April 2002",
    xaxis = list(title = "Week of April 2002"),
    yaxis = list(title = "Max Temperature (°C)"),
    showlegend = FALSE)
```

### Chart C

```{r}
# bar chart of daily average precipitation in April 2002
daily_avg_prcp = 
  ny_noaa_2002_apr |>
  group_by(date) |>
  summarize(
    avg_prcp = mean(prcp_mm, na.rm = TRUE)) |>
  ungroup()

daily_avg_prcp |>
  plot_ly(
    x = ~date,
    y = ~avg_prcp,
    type = "bar",
    text = ~paste("Date:", date, 
                  "<br>Avg Precip:", round(avg_prcp, 1), "mm"),
    textposition = "none",                        
    hovertemplate = "%{text}<extra></extra>",
    marker = list(color = ~avg_prcp, colorscale = "Cividis")) |>
  layout(
    title = "Daily Average Precipitation in April 2002",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Average Precipitation (mm)"))
```

