---
title: "NY Weather Dashboard: April 2002"
output: html_document
---

[Return to Homepage](index.html)

first we load all necessary libraries
```{r message=FALSE}
library(tidyverse)
library(plotly)
library(lubridate)
library(p8105.datasets)
data(ny_noaa)
```

# Problem2
Create a flexdashboard using plotly for that includes at least three distinct plot types (e.g. scatterplots, line plots, bar plots, box plots, etc.). Use one of the following datasets, and load from the p8105.datasets package:

```{r}
ny_noaa_2002_apr =
  ny_noaa |>
  janitor::clean_names() |>
  #only analysis data from April 2002 and drop missing data
  mutate(date = ymd(date)) |>
  filter(year(date) == 2002 & month(date) == 04) |>
  filter(!is.na(prcp) & !is.na(snow) & !is.na(snwd) & !is.na(tmax) & !is.na(tmin)) |>
  mutate(across(c(prcp, snow, snwd, tmin, tmax), as.numeric),
    #convert from tenths of units to standard units (mm and °C)
    prcp_mm = prcp / 10,
    tmax_c = tmax / 10,
    tmin_c = tmin / 10)
```


```{r}
#create scatterplot of the relationship between snowfall and precipitation in April 2002
ny_noaa_2002_apr |>
  mutate(
    text_label = str_c(
      "ID: ", id,
      "\nDate: ", date, 
      "\nPrecipitation (mm): ", prcp_mm,
      "\nSnowfall (mm): ", snow,
      "\nSnow Depth (mm): ", snwd)) |>
  plot_ly(
    x = ~prcp_mm, 
    y = ~snow, 
    color = ~snwd,
    text = ~text_label,
    hoverinfo = 'text',
    type = "scatter", 
    mode = "markers", 
    alpha = 0.7) |>
  layout(
    title = "Snowfall vs. Precipitation (April 2002)",
    xaxis = list(title = "Precipitation (mm)"),
    yaxis = list(title = "Snowfall (mm)")) |>
  colorbar(title = "Snow Depth (mm)")
```

```{r}
#Box Plot for showing max temperature distribution of 4 weeks in April 2002
ny_noaa_2002_apr |>
  mutate(
    week_of_month = case_when(
      day(date) <= 7  ~ "Week 1",
      day(date) <= 14 ~ "Week 2",
      day(date) <= 21 ~ "Week 3",
      TRUE            ~ "Week 4"),
    week_of_month = factor(week_of_month, 
                           levels = c("Week 1", "Week 2", "Week 3", "Week 4"))) |>
  plot_ly(
    x = ~week_of_month, 
    y = ~tmax_c, 
    type = "box",
    color = ~week_of_month) |>
  layout(
    title = "Distribution of Weekly Highest Temperatures in April 2002",
    xaxis = list(title = "Week of April 2002"),
    yaxis = list(title = "Max Temperature (°C)"),
    showlegend = FALSE)
```

# Bar Chart for 2002
```{r}

```



